apiVersion: v1
kind: Service
metadata:
  name: jt-education-frontend-management
  namespace: ${JT_MGM_NAMESPACE}
spec:
  type: NodePort
  ports:
    - port: 8082
      protocol: TCP
      targetPort: 8080
  selector:
    app: jt-education-frontend-management
